""" Generates a directory """

import sys
import os
import os.path
import subprocess as sp

string = '''
    // Generated by cwd.py
    #pragma once
    #define TEST_DIR "{}"

    // Returns full pathname to asset file
    #define ASSET_FILE(filename) TEST_DIR "/assets/" filename
    #define CONFIG_FILE(filename) TEST_DIR "/configs/" filename
    #define SHADER_FILE(filename) TEST_DIR "/shaders/" filename
    #define TEXTURE_FILE(filename) TEST_DIR "/textures/" filename
    #define MODEL_FILE(filename) TEST_DIR "/models/" filename
'''.format(os.getcwd())

with open(sys.argv[1], 'w') as f:
    f.write(string)

sp.run(['clang-format', '-i', sys.argv[1]], check=True)