
// Generated by cwd.py
#pragma once
#define TEST_DIR "/home/rksht/samples/logl/test"

// Returns full pathname to asset file
#define ASSET_FILE(filename) TEST_DIR "/assets/" filename
#define CONFIG_FILE(filename) TEST_DIR "/configs/" filename
#define SHADER_FILE(filename) TEST_DIR "/shaders/" filename
#define TEXTURE_FILE(filename) TEST_DIR "/textures/" filename
#define MODEL_FILE(filename) TEST_DIR "/models/" filename
